<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Stasis.Content\Stasis.Content.csproj" />
    <ProjectReference Include="..\Stasis.Engine\Stasis.Engine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract >true</IncludeNativeLibrariesForSelfExtract>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
